
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.ariel-os]
url = "https://raw.githubusercontent.com/ariel-os/ariel-os/main/supply-chain/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.88"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-rs]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.42.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.57"
criteria = "safe-to-deploy"

[[exemptions.cmake]]
version = "0.1.58"
criteria = "safe-to-deploy"

[[exemptions.cookie]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.cookie_store]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.1.9"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locale_core]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.idna_adapter]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.35"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.185"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.33"
criteria = "safe-to-deploy"

[[exemptions.potential_utf]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.37"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.13"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.serde_path_to_error]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.simd-adler32]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.53"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.31"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.50.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-flame]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ureq]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.ureq-proto]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.8"
criteria = "safe-to-deploy"

[[exemptions.utf8-zero]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.yoke-derive]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.zerotrie]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.11.6"
criteria = "safe-to-deploy"

[[exemptions.zerovec-derive]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.21"
criteria = "safe-to-deploy"
